/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tutego_jni_StrLen */

#ifndef _Included_com_tutego_jni_StrLen
#define _Included_com_tutego_jni_StrLen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tutego_jni_StrLen
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tutego_jni_StrLen_strlen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
