/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 05.06.2010, 12:25:38
 */

package com.tutego.insel.ui.bing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Christian
 */
@SuppressWarnings("all")
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        minutesSlider.setValue( 1 );
        minutesTextField.setText( "1" );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        timeToMsgLabel = new javax.swing.JLabel();
        minutesSlider = new javax.swing.JSlider();
        minutesTextField = new javax.swing.JTextField();
        minutesLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        remainingLabel = new javax.swing.JLabel();
        remainingMinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BING");

        timeToMsgLabel.setText("Zeit bis zur Meldung:");

        minutesSlider.setMaximum(1440);
        minutesSlider.setMinimum(1);
        minutesSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minutesSliderStateChanged(evt);
            }
        });

        minutesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesTextFieldActionPerformed(evt);
            }
        });

        minutesLabel.setText("Minuten");

        exitButton.setText("Beenden");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        remainingLabel.setText("Verbleibende Zeit:");

        remainingMinLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(minutesSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesLabel))
                    .addComponent(timeToMsgLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remainingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remainingMinLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minutesLabel)
                        .addComponent(minutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeToMsgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remainingLabel)
                    .addComponent(remainingMinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void minutesSliderStateChanged(javax.swing.event.ChangeEvent evt) {
        minutesTextField.setText( "" + minutesSlider.getValue() );
    }

    private void minutesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        try
        {
            minutesSlider.setValue( Integer.parseInt( minutesTextField.getText() ) );
        }
        catch ( NumberFormatException e ) { }
    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {

        startButton.setEnabled( false );
        
        final long start = System.currentTimeMillis();
        final long end   = start + minutesSlider.getValue() * 60 * 1000;

        final Timer timer = new Timer( 100, null );
        timer.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                long now = System.currentTimeMillis();
                if ( now >= end )
                {
                    remainingMinLabel.setText( "" );
                    startButton.setEnabled( true );
                    JOptionPane.showMessageDialog( null, "BING!" );
                    timer.stop();
                }
                else
                    remainingMinLabel.setText( (end - now) / 1000 + " Sekunden" );
            }
        });
        timer.start();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JSlider minutesSlider;
    private javax.swing.JTextField minutesTextField;
    private javax.swing.JLabel remainingLabel;
    private javax.swing.JLabel remainingMinLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel timeToMsgLabel;
    // End of variables declaration

}
